### PR TITLE
Add Swift 3 support

### PR DESCRIPTION
**Pull request by evgenbakumenko**

### CODE REVIEW

**Comment by PaulTaykalo** [comment]
@evgenbakumenko lgtm

**Comment by PaulTaykalo** [comment]
@evgenbakumenko fix all the tests

**Comment by evgenbakumenko** [comment]
@PaulTaykalo fixed

**Comment by roman-mazur** [comment]
@evgenbakumenko should be submitted against Keypr/helium project.

**Comment by evgenbakumenko** [comment]
@roman-mazur will do

**Pull request closed without merging**
